### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by farishkash** [Rishirandhawa/teacozy#4]
```
        <div class="header-nav">
            <a href="#">Mission</a>
            <a href="#">Featured Tea</a>
            <a href="#">Locations</a>
        </div>
```

At this point the nav bar should be working for in page linking.  You should assign each section an id and then target that with the nav bar link.

**Comment by Rishirandhawa** [comment]
oops ... sorry I forgot to add the in-links to specific ID's.
