### ISSUE TITLE
Location section

### ISSUE THREAD

**Issue by farishkash** [Rishirandhawa/teacozy#5]
The text inside of the boxes need to be centered vertically.  Also the boxes themselves should be up a little bit higher.

![tea_cozy](https://user-images.githubusercontent.com/5844161/33974338-d6992154-e03c-11e7-87d6-7ab928584b8d.png)

**Comment by Rishirandhawa** [comment]
oh..ok.. so perhaps I should have positioned them relative and moved them a bit higher. Noted. Thanks
