### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Rishirandhawa/teacozy#6]
Overall met expectations.

Using alt text is about accessibility for the visually impaired on the web.
Comments for organization is about using best practices is coding a website.

The project needs some minor adjustments in spacing.  

Also to prepare you for the final projects, look at media queries. See if you can make this site fit inside of a mobile device by using one. You will be doing this heavily in your final projects.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

https://www.w3schools.com/css/css3_mediaqueries_ex.asp

**Comment by Rishirandhawa** [comment]
Many thanks for the feedback. Its very helpful and I will implement all suggestions and recommendations. Will also implement this site in media queries for mobile implementation
